CREATE TABLE WebPages
(
	[Id]				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Title]				NVARCHAR(1000) NOT NULL,
	[Description]		NVARCHAR(4000) NOT NULL,
	[Category]			NVARCHAR(500) NULL,
	[Link]				VARCHAR(1000) NOT NULL
)
